### ISSUE TITLE
investiguer et corriger la note HTTP du dashlord

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1407]
cf [src](https://stackoverflow.com/questions/31661449/express-js-how-to-set-a-header-to-all-responses) utiliser un middleware pour ajouter des headers partout

```[tasklist]
### Tasks
- [x] CSP header
- [x] HSTS header http -> https redirection
- [x] XFO header
- [x] ~X-XSS protection header~
- [x] X-Content-Type-Options
```

**Comment by alice-telescoop** [comment]
| header key              | api                                          | front                                        | 
|-------------------------|----------------------------------------------|----------------------------------------------|
| Content-Security-Policy | `default-src 'none'`                           | cf ci-dessous                                | 
| HSTS                    | `max-age=63072000; includeSubDomains; preload` | `max-age=63072000; includeSubDomains; preload` | 
| XFO                     | DENY                                         | DENY                                         | 
| ~X-XSS~                 | :x:                                          | :x:                                          | 
| X-Content-Type-Options  | `nosniff`                                    | `nosniff`                                    |

**Comment by alice-telescoop** [comment]
https://docs.crisp.chat/guides/others/whitelisting-our-systems/crisp-domain-names/

**Comment by alice-telescoop** [comment]
https://owasp.org/www-project-secure-headers
https://github.com/ovh/venom#installing

si on veut aller plus loin plus tard
