### ISSUE TITLE
Page PROFIL

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1667]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/api-subventions-asso/issues/1674
- [ ] https://github.com/betagouv/api-subventions-asso/issues/1675
- [ ] https://github.com/betagouv/api-subventions-asso/issues/1677
- [ ] https://github.com/betagouv/api-subventions-asso/issues/1678
- [ ] https://github.com/betagouv/api-subventions-asso/issues/1124
- [ ] https://github.com/betagouv/api-subventions-asso/issues/1679
```

**Comment by alice-telescoop** [comment]
Ça marche de reprendre les composants d'étape mais vraisemblablement pas en phase avec le design
