### ISSUE TITLE
EPIC: intégrer les associations par RID et T.A.H.I.T.I.

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1932]
## Définitions
RID : 6 ou 7 chiffres identifiant une association
RIDET : RID + 3 chiffres identifiant un établissement
T.A.H.I.T.I : [(6 chiffres) ou (1 lettre et 5 chiffres)] + 3 chiffres identifiant un établissement
On a les listes des assos et établissements pour T.A.H.I.T.I.[^1] et RID/RIDET[^2]

On sait distinguer les associations parmi l'ensemble des structures enregistrées. En effet, la catégorie juridique qu'on connaît pour les Siren est renseignée selon la même nomenclature.

- **existe-t-il un accès par association (et non par établissement) aux associations relevant du code T.A.H.I.T.I ?**

## Informations générales sur les structures
- on dispose déjà d'une base de noms pour les deux systèmes d'identifiants [^1][^2]
- le répertoire T.A.H.I.T.I. dispose des adresse
- le répertoire RIDET ne dispose que de la ville 
    - **où trouver le reste?**
- les associations relevant de ces registres disposent aussi d'un RNA
    - le format est légèrement différent : on a parfois des lettres en 3e position.
    - [ ] formaliser et implémenter une nouvelle règle de détections des RNA, qui inclue les RNA des COM #1931 
- **où trouver des mapping avec le rna ?**

## Refacto des identifiants
*Ce qui suit est écrit pour les associations mais est à faire pour les établissements de la même façon*

- [ ] définir une entité `AssoIdentifiers` qui contiendrait tous les identifiants connus d'une association
    ```ts
    type AssoIdentifiers = {
        rna?: Rna;
        siren?: Siren;
        rid?: Rid;
        tahiti: Tahiti;
    }
    ````
- [ ] transformer les interfaces de provider pour que les seules méthodes publiques soient de la forme `get(identifier: AssoIdentifier)`. Ces méthodes-là se chargeraient d'appeler les providers de données par les identifiants pertinents.
- [ ] définir une classe par type d'identifiant pour que
    - chaque classe ait son validateur et son constructeur qui nous protège de problème de format et nous dispense de multiplier les validations partout dans le code
    - distinguer des identifiants qui correspondent aux même regex (ex: Ridet/T.A.H.I.T.I/Siren)
- [ ] transformant la table `rna-siren` en `asso-identifiers` pour matcher tous types d'identifiants d'association.
- [ ] transformer nos routes `/associations/[identifiiant]` en `associations/[type d'identifiant]/[identifiant]` pour ne pas risquer de confondre notamment des T.A.H.I.T.I. et des RIDET
    - [ ] sur le front
    - [ ] sur l'api
    - [ ] extraire la reconnaissance de l'identifiant pour pouvoir maintenir les anciennes routes pour les consommateurs

### chorus
chorus met des `#` quand le SIRET n'est pas présent. Une nouvelle colonne "No TVA 3 (COM-RIDET ou TAHITI)" peut être ajoutée à l'extract (on ne l'a pas pour l'instant) pour donner cette information. Dans un fichier d'exemple, quelques cas ne correspondent ni à un RIDET ni à un code T.A.H.I.T.I. . Dans un cas on a un RNA.
- FRWFEP
- FRWFCTUGSEL
- FRWFINSERTION
- FRWFCOMITEDESFETES
Reste à comprendre
- **comment distinguer les RIDET et les T.A.H.I.T.I. sur l'extract chorus ?**

### compte asso
le compte asso ajoute `99` devant les Rid pour en faire des pseudos Siren[^3]
- **les rid transformés en siren par le compte assos peuvent-ils être en conflit avec des "vrais" siren ?**  → oui ! (source : insee 25/01)
- **se passe-t-il la même chose pour les TAHITI ?**
- Piste : pour `getByRidet` : appeler notre route habituelle en rajoutant `99` à la requête ?  → bof du coup

### osiris
- [ ] vérifier qu'il fait la même chose que le compte asso

### fonjep
- Bcp de lignes contiennent des zéros : **est-ce en lien ?** → p-ê mais ça se confond avec les identifiant SIREN/T
- Des Ridet sont parfois renseignés. On ne les importe pas dans nos bases
    - [ ] réimporter les données FONJEP manquantes contenant un Ridet
- **qu'est-il fait pour les T.A.H.I.T.I ?**

[^1]: [répertoire T.A.H.I.T.I.](https://www.data.gouv.fr/fr/datasets/repertoire-des-entreprises/)
[^2]: [RID/RIDET](https://data.gouv.nc/explore/dataset/entreprises-actives-au-ridet/information/)
[^3]: [FAQ Compte Asso](https://lecompteasso.associations.gouv.fr/faq/integration-asso-dans-compte/) sur le sujet

**Comment by VSerain** [comment]
Les données de l'api asso provenant en partie du compte asso/osiris voir si on a aussi un truc à gérer ici

**Comment by mxmeunier** [comment]
Réunion avec l'INSEE le 25 janvier

**Comment by VSerain** [comment]
Je déplace dans le BL PO

**Comment by VSerain** [comment]
Dans osiris = un ridet = un siret - 99 au debut
