### ISSUE TITLE
Préparer premiers entretiens user

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#2046]
```[tasklist]
### Tasks
- [ ] Prépa intro protocole de test
- [ ] Définir axe : la provenance de nos données et comment elles sont retranscrites sur notre outil
- [ ] Définir axe : démontage produit
- [ ] Préparer doc de suivi des ITW et doc de CR
```
