### ISSUE TITLE
WordPress : révisions et création pages

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#694]
Pour préparer notre échange tout à l'heure, voilà que je note de mon côté sur notre to-do avant la publication de la nouvelle page d'accueil :
- Mettre à jour la carte de France avec les % par région
- Mettre plus d'avis (en s'aidant du [livre d'or](https://docs.google.com/document/d/1E056EIK6mQbKxvJ-qgfvUCV46N9yUDFB2gUme6WlCSU/edit))
- Insérer la section API telle qu'elle est présentée dans le Figma
- Publier la page API
- Présenter à l'équipe

Et en to-do complémentaire (pas impératif mais si c'est publié c'est mieux) : 
- Relier la mise à jour des chiffres clés à Matomo
- Relier la carte de France avec les % par région à Matomo
- Publier les onglets revisités
```[tasklist]
### Tasks
- [ ] Mettre à jour la carte de France avec les % par région
- [x] Mettre plus d'avis (en s'aidant du livre d'or)
- [x] Insérer la section API telle qu'elle est présentée dans le Figma
- [ ] Publier la page API
- [ ] Présenter à l'équipe
- [ ] Relier la mise à jour des chiffres clés à Matomo
- [ ] Publier les onglets revisités
- [ ] Relier la carte de France avec les % par région à Matomo
```

**Comment by Gttnmarion** [comment]
Plateforme de consultation
API
Notre opendata
